trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: AzureWebAppContainer@1
    displayName: Deploy Docker Compose app
    inputs:
      azureSubscription: "isskin-backend-connection"
      appName: "isskin-backend-app"
      multicontainerConfigType: "Compose"
      multicontainerConfigFile: "docker-compose.yml"
